// Stable section and question IDs keep review answers independent of code drafts.
const choice=(id,prompt,answers,revisit)=>({id,type:'choice',prompt,options:answers.map(([text,feedback],i)=>({id:String(i),text,feedback,correct:i===0})),revisit});
const blank=(id,prompt,code,accept,explanation,hint,revisit)=>({id,type:'blank',prompt,code,accept,explanation,hint,revisit});
export const sections=[
  {id:'S1',chapter:1,title:'Classes and objects',intro:{
    hook:'Build a wizard from your own JavaScript class.',build:'A `Wizard` class and two objects with separate data.',
    objectives:['explain the difference between a class and an object','write a constructor that sets a property','use `new` to create independent objects'],
    summary:'A class is a reusable description. `new` creates an object from it. The `constructor` sets a property (also called an attribute) on that object; `this` means the object being created.',
    prerequisites:'No JavaScript classes needed yet. A variable is a name for a value; you will see one in the example.',
    concepts:[['class','A reusable description for making objects.'],['object','One particular thing created from a class.'],['constructor','A special function that runs when `new` creates an object.'],['parameter','An input a function receives, such as `colour`.'],['this','The particular object being created or used.'],['property (also called an attribute)','A named piece of data stored on an object.']],
    example:{code:'class Potion {\n  constructor(colour) {\n    this.colour = colour;\n  }\n}\n\nconst redPotion = new Potion("red");\nconst bluePotion = new Potion("blue");',check:'redPotion.colour === "red" && bluePotion.colour === "blue"',walkthrough:['`class Potion` describes what each potion has. No potion exists yet.','`new Potion("red")` creates one potion and gives `colour` the value `"red"`.','`this.colour` stores the value on that new object. The second `new` makes a separate object.'],result:'`redPotion.colour` is `"red"`; `bluePotion.colour` is `"blue"`.'},predict:['If you change `bluePotion.colour` to `"green"`, what is `redPotion.colour`?','Still `"red"`. Each object keeps its own property.'],assignmentLink:'Your Unit 4 report asks you to explain classes. You can describe a class as a blueprint and an object as one instance made with `new`.'},
    review:{questions:[
      choice('S1-Q1','What is the difference between a class and an object?', [['A class is a reusable description; an object is one thing made from it.','Correct. One class can create many objects.'],['They are the same thing.','One class can create several separate objects.'],['An object describes a class.','The class is the description used to create an object.']], 'C1.1a'),
      choice('S1-Q2','In `constructor(name) { this.name = name; }`, what does `this` mean?', [['The new object being created.','Correct. The property belongs to this particular object.'],['The `Wizard` class itself.','The class describes objects; `this` refers to one object.'],['Every wizard ever created.','Each new wizard has its own properties.']], 'C1.1b'),
      choice('S1-Q3','If `apprentice.name` changes, what happens to `wizard.name`?', [['It stays the same.','Correct. The two objects are independent.'],['It changes too.','Changing one object does not change another.'],['It becomes undefined.','The first object still has its own name.']], 'C1.2'),
      blank('S1-Q4','Create an object from a class.','const wizard = ____ Wizard("Aster");',['new'],'Correct. `new` creates an object.','Which keyword creates a fresh object?','C1.1c'),
      blank('S1-Q5','Name the function that runs when an object is created.','class Wizard {\n  ____(name) {\n    this.name = name;\n  }\n}',['constructor'],'Correct. The constructor sets starting properties.','It runs automatically after `new`.','C1.1b'),
      blank('S1-Q6','Start a class declaration.','____ Wizard {\n}',['class'],'Correct. JavaScript uses lowercase `class`.','Check the keyword and its case.','C1.1a')]}},
  {id:'S2',chapter:2,title:'Properties: defaults and your own object',intro:{
    hook:'Give every wizard starting equipment, then customise your own.',build:'Six default properties and your own choices.',
    objectives:['set default properties in a constructor','customise one object with dot notation','distinguish strings from numbers'],prerequisites:'Remember: a class creates objects with `new`, and `this` refers to the object being set up.',
    summary:'A default value is set in the constructor for every new object. Dot notation, such as `wizard.wand`, changes a property on just one object.',
    concepts:[['default value','The starting value a constructor gives every new object.'],['dot notation','`object.property` reads or changes one property on one object.'],['assignment (`=`)','Stores a value.'],['string','Text in quotes, such as `"grey"`.'],['number','A value such as `3`, without quotes.']],
    example:{code:'class Potion {\n  constructor(colour) {\n    this.colour = colour;\n    this.size = "small";\n    this.strength = 1;\n  }\n}\n\nconst potion = new Potion("red");\npotion.size = "large";\npotion.strength = 3;',check:'potion.size === "large" && potion.strength === 3 && new Potion("blue").size === "small"',walkthrough:['The constructor gives every potion size `"small"` and strength `1`.','`potion.size = "large"` changes only this potion.','`3` is a number; `"large"` is text.'],result:'This potion is large with strength 3. A new potion still starts small with strength 1.'},predict:['What size is `new Potion("gold")`?','`"small"`. Changing one object does not rewrite the constructor.'],assignmentLink:'String and number properties give you examples of types and data for your Unit 4 report.'},
    review:{questions:[
      choice('S2-Q1','Where do you put `this.wand = "oak";` so every new wizard starts with an oak wand?', [['Inside the constructor.','Correct. It sets a class default for every new object.'],['After `const wizard = new Wizard(...)`.','That changes just one object.'],['In `actions.js`.','That file is for calls later in the course.']], 'C2.3a'),
      choice('S2-Q2','The default wand is oak. You set `wizard.wand = "crystal";`. What wand does a fresh wizard get?', [['`"oak"`','Correct. The constructor still sets oak.'],['`"crystal"`','Only the existing `wizard` changed.'],['No wand.','The constructor still adds the wand.']], 'C2.3b'),
      choice('S2-Q3','Which line sets the level to the number 3?', [['`wizard.level = 3;`','Correct. Numbers have no quotes.'],['`wizard.level = "3";`','Quotes make it text.'],['`wizard.level == 3;`','That compares values instead of assigning.']], 'C2.6b'),
      blank('S2-Q4','Set the workshop cloak default.','this.cloakColour = "____";',['grey'],'Correct. `grey` is a workshop choice; JavaScript itself allows other strings.','Check the property reference for the default colour.','C2.1a'),
      blank('S2-Q5','Customise only one object.','wizard____cloakPattern = "stars";',['.'],'Correct. The dot connects an object and its property.','Which symbol connects an object to a property?','C2.2b'),
      blank('S2-Q6','Set the level default.','this.____ = 1;',['level'],'Correct. Every new wizard starts at level 1.','Which property stores the level?','C2.6a')]}},
  {id:'S3',chapter:3,title:'Methods and decisions',intro:{
    hook:'Make your wizard cast spells, recover health and level up.',build:'Methods in `character.js` and calls in `actions.js`; your earlier code stays safe.',
    objectives:['write and call a method','use decisions and `return` values','update a property from its current value'],prerequisites:'Remember: properties belong to objects, and `this` refers to the object using the method.',
    summary:'A method — a function that belongs to a class — runs when an object calls it. `if` chooses what happens; `return` sends a result back.',
    concepts:[['method — a function that belongs to a class','Describes something its objects can do.'],['calling a method','Running it with brackets, such as `potion.drink()`.'],['return','Sends a result back from a method.'],['conditional','`if` and `else` choose code using a true or false test.'],['`===`','Checks equality; `=` stores a value.']],
    example:{code:'class Potion {\n  constructor(colour) {\n    this.colour = colour;\n    this.sips = 3;\n  }\n\n  drink() {\n    if (this.sips > 0) {\n      this.sips = this.sips - 1;\n    }\n    return this.sips;\n  }\n}\n\nconst potion = new Potion("red");\npotion.drink();\npotion.drink();',check:'potion.sips === 1',walkthrough:['`drink()` is inside the class, after the constructor.','The `if` stops sips falling below zero.','`return` gives back the number of sips. The two calls make the method run twice.'],result:'After two calls, `potion.sips` is `1`.'},predict:['What happens after five calls to `drink()`?','The value stops at `0`; the `if` prevents a negative number.'],assignmentLink:'Your Unit 4 report asks you to annotate methods and selection. Explain how a method uses an `if` decision.'},
    review:{questions:[
      choice('S3-Q1','What is a method?', [['A function that belongs to a class.','Correct. Objects made from the class can call it.'],['A property storing a number.','A property stores data; a method performs an action.'],['A second name for the constructor.','A constructor runs on creation; other methods are called later.']], 'C3.1a'),
      choice('S3-Q2','Where does `castSpell()` belong?', [['Inside the `Wizard` class, after its constructor.','Correct. It must be inside the class but outside the constructor.'],['Inside the constructor.','Close the constructor before defining the method.'],['Below `const wizard = new Wizard(...)`.','That is outside the class.']], 'C3.1a'),
      choice('S3-Q3','Why does defining `castSpell()` alone show no spell?', [['It still needs a call such as `wizard.castSpell();`.','Correct. A method runs when it is called.'],['All methods run automatically.','Only the constructor runs on object creation.'],['The class needs a new name.','The method needs a call, not a new class name.']], 'C3.1b'),
      choice('S3-Q4','Which checks whether the power is ice?', [['`this.specialPower === "ice"`','Correct. `===` compares values.'],['`this.specialPower = "ice"`','A single `=` assigns a value.'],['`this.specialPower === ice`','Without quotes, `ice` would be a variable.']], 'C3.2b'),
      blank('S3-Q5','Send a result back.','castSpell() {\n  ____ this.specialPower;\n}',['return'],'Correct. `return` sends a value back.','Which keyword gives back a result?','C3.1a'),
      blank('S3-Q6','Call the method in `actions.js`.','wizard.____();',['castSpell'],'Correct. The name must match the class method.','Check the method name and its capital S.','C3.1b'),
      blank('S3-Q7','Recover twenty health.','this.health = this.health ____ 20;',['+'],'Correct. This adds 20 to the current value.','Which operator adds numbers?','C3.3b'),
      blank('S3-Q8','Check whether the level is below 20.','if (this.level ____ 20) {\n  this.level = this.level + 1;\n}',['<'],'Correct. The comparison stops level 20 increasing.','Which comparison means “less than”?','C3.4a')]}},
  {id:'S4',chapter:4,title:'Inheritance: sharing code',intro:{
    hook:'Share code between your wizard and goblin instead of copying it.',build:'A `Character` parent class used by `Wizard` and `Goblin`.',
    objectives:['spot code both classes need','use `extends` and `super` to share it','explain why shared code is easier to maintain'],prerequisites:'Remember that a class describes objects and a method belongs to a class.',
    summary:'Inheritance lets a child class reuse a parent class’s code. `extends` connects the classes; `super` runs the parent constructor.',
    concepts:[['duplication','The same code copied in several places.'],['parent class','A class whose features another class can inherit.'],['child class','A class that inherits from a parent.'],['extends','Connects a child class to its parent.'],['super','Calls the parent constructor before the child uses `this`.']],
    example:{code:'class Item {\n  constructor(name, weight) {\n    this.name = name;\n    this.weight = weight;\n  }\n\n  describe() {\n    return this.name + " weighs " + this.weight;\n  }\n}\n\nclass Potion extends Item {\n  constructor(name) {\n    super(name, 1);\n    this.colour = "red";\n  }\n}\n\nconst potion = new Potion("Healing draught");\npotion.describe();',check:'potion.describe() === "Healing draught weighs 1"',walkthrough:['`Item` holds what every item shares.','`Potion extends Item` means a potion inherits from Item.','`super(name, 1)` sets the inherited name and weight.','`Potion` inherits `describe()` without copying it.'],result:'`potion.describe()` returns `"Healing draught weighs 1"`.'},predict:['Does `Potion` need its own `describe()`?','No. It inherits the method from `Item`.'],assignmentLink:'Inheritance is an example of maintainability for your Unit 4 report: fix shared code in one place.'},
    review:{questions:[
      choice('S4-Q1','Why create a `Character` class?', [['To write shared properties and methods once.','Correct. Wizard and Goblin can reuse them.'],['To make JavaScript run faster.','The aim here is reuse and easier maintenance.'],['Because every class must have a parent.','JavaScript allows classes without a parent.']], 'C4.1'),
      choice('S4-Q2','What does `super(name, 100)` do in `Wizard`?', [['Calls the parent constructor with those values.','Correct. The parent sets shared starting data.'],['Creates a second wizard.','It sets up the current wizard through its parent.'],['Copies every method into the source file.','Inherited methods stay defined in the parent.']], 'C4.3a'),
      choice('S4-Q3','Why does `wizard.recoverHealth()` work after removing its copy from `Wizard`?', [['Wizard inherits the method from Character.','Correct. `extends` provides the parent method.'],['The browser remembered the deleted code.','A fresh Run rebuilds objects from current code.'],['`actions.js` defines the method.','That file calls the method; Character defines it.']], 'C4.3c'),
      blank('S4-Q4','Make Goblin inherit Character.','class Goblin ____ Character {',['extends'],'Correct. `extends` connects the child and parent.','Which keyword establishes inheritance?','C4.4'),
      blank('S4-Q5','Call the parent constructor.','____(name, 60);',['super'],'Correct. `super` sets up parent properties.','Which keyword calls the parent constructor?','C4.4'),
      blank('S4-Q6','Stop health below zero.','this.health = Math.max(____, this.health - amount);',['0'],'Correct. `Math.max` picks zero when the subtraction is negative.','What is the minimum health?','C4.5')]}},
  {id:'S5',chapter:5,title:'Objects working together',intro:{
    hook:'Make your wizard’s spell affect the goblin.',build:'A targeted spell and a battle script you design.',
    objectives:['pass an object into a method','call a method on that object','predict the result of actions in order'],prerequisites:'Remember: a method runs when called, and `this` refers to the object making the call.',
    summary:'An argument passes an object into a method. Inside the method, a parameter such as `target` names that object, so it can be asked to act.',
    concepts:[['parameter','A named slot in a method’s brackets, such as `target`.'],['argument','The value passed into a method call. It fills the parameter.'],['variable (`let`)','A named box for a value that can change later.'],['return','Sends a value back and stops the method straight away.'],['sequence','Actions run from top to bottom in order.']],
    example:{code:'class Patient {\n  constructor(name) {\n    this.name = name;\n    this.health = 40;\n  }\n\n  receiveHealing(amount) {\n    this.health = this.health + amount;\n  }\n}\n\nclass Healer {\n  constructor(name) {\n    this.name = name;\n    this.power = 15;\n  }\n\n  heal(target) {\n    target.receiveHealing(this.power);\n  }\n}\n\nconst healer = new Healer("Wren");\nconst patient = new Patient("Pip");\nhealer.heal(patient);',check:'patient.health === 55',walkthrough:['`heal(target)` receives an object. Here `target` is `patient`.','The target’s `receiveHealing` method changes its health.','`patient` has no quotes because it is the object, not the word.'],result:'`patient.health` rises from 40 to 55.'},predict:['What is the health after two healing calls?','`70`. Each call adds 15.'],assignmentLink:'Object interaction is a useful example when comparing object-oriented and procedural code in your Unit 4 report.'},
    review:{questions:[
      choice('S5-Q1','In `wizard.castSpell(goblin)`, what is `target`?', [['The goblin object.','Correct. The argument becomes the target parameter.'],['The text `"goblin"`.','There are no quotes around the object argument.'],['The Wizard class.','The target is the object passed to the method.']], 'C5.1b'),
      choice('S5-Q2','Why is `wizard.castSpell("goblin")` wrong here?', [['It passes text, which has no `takeDamage` method.','Correct. Pass the goblin object without quotes.'],['It needs single quotes.','Either quote style still creates text.'],['Methods cannot receive arguments.','The method has a target parameter.']], 'C5.1b'),
      choice('S5-Q3','A level-3 fire wizard hits a goblin at 60 health. Damage is `12 + level * 2`. What health remains?', [['42','Correct. Damage is 18, and 60 − 18 = 42.'],['48','That leaves out the level bonus.'],['18','That is the damage, not the remaining health.']], 'C5.1e'),
      choice('S5-Q4','If you press Run twice without editing, does the goblin keep losing health?', [['No. Each Run creates fresh objects.','Correct. The same script starts from fresh state each time.'],['Yes. Damage accumulates across runs.','Each Run starts over.'],['Only after refreshing the page.','Refreshing does not change how Run starts.']], 'C5.3'),
      blank('S5-Q5','Damage the target.','target.____(damage);',['takeDamage'],'Correct. The target handles its own health.','Which shared method reduces health?','C5.1a'),
      blank('S5-Q6','Make the goblin hit the wizard.','goblin.attack(____);',['wizard'],'Correct. Pass the object without quotes.','Which object is being attacked?','C5.2'),
      blank('S5-Q7','Use the wizard’s level in ice damage.','damage = 10 + this.____ * 2;',['level'],'Correct. `this.level` reads the current wizard’s level.','Which property stores the level?','C5.1e')]}},
];
export const sectionByChapter=Object.fromEntries(sections.map(section=>[section.chapter,section]));
export const questionById=Object.fromEntries(sections.flatMap(section=>section.review.questions.map(question=>[question.id,question])));
